//! The listener is TLS-only and loopback-only (`SECURITY.md` §6, test ids S-02, S-03).

// Not an engine crate: tests here legitimately touch sockets, the clock and files.
#![allow(
    clippy::disallowed_types,
    clippy::disallowed_methods,
    clippy::disallowed_macros
)]

mod support;

use std::net::{Ipv4Addr, Ipv6Addr, SocketAddr};

use pfp_server::{issue, AcceptLimits};
use support::{
    client_trusting, eventually, raw_exchange, read_greeting, tls_connect, TestServer, GREETING,
    SOON,
};
use time::OffsetDateTime;
use tokio::io::AsyncReadExt;
use tokio::net::TcpStream;

fn contains(haystack: &[u8], needle: &[u8]) -> bool {
    haystack.windows(needle.len()).any(|w| w == needle)
}

#[tokio::test]
async fn client_trusting_only_the_ephemeral_ca_completes_a_handshake() {
    let server = TestServer::start();
    let config = client_trusting(&server.material.ca_cert_der);

    // The canonical origin is the IP literal; `localhost` is in the SANs for completeness.
    for name in ["127.0.0.1", "localhost"] {
        let mut stream = tls_connect(server.addr, config.clone(), name)
            .await
            .unwrap_or_else(|error| panic!("handshake for {name}: {error}"));
        {
            let (_, session) = stream.get_ref();
            assert_eq!(
                session.protocol_version(),
                Some(rustls::ProtocolVersion::TLSv1_3)
            );
            assert_eq!(session.alpn_protocol(), Some(&b"http/1.1"[..]));
            // The server presents the leaf and only the leaf.
            let presented = session.peer_certificates().unwrap();
            assert_eq!(
                presented,
                std::slice::from_ref(&server.material.leaf_cert_der)
            );
        }
        assert_eq!(read_greeting(&mut stream).await, GREETING);
    }

    eventually("both handshakes counted", || {
        server.stats.handshakes_completed() == 2
    })
    .await;
    assert_eq!(server.stats.handshakes_failed(), 0);
    server.stop().await;
}

#[tokio::test]
async fn client_that_does_not_trust_the_ca_fails() {
    let server = TestServer::start();

    // Trusts a different CA generated by the very same code: same names, same
    // parameters, another key. It must not verify this server.
    let other = issue(OffsetDateTime::now_utc()).unwrap();
    let error = tls_connect(
        server.addr,
        client_trusting(&other.ca_cert_der),
        "127.0.0.1",
    )
    .await
    .expect_err("an untrusted issuer must fail the handshake");
    let text = format!("{error:?}");
    assert!(text.contains("UnknownIssuer"), "{text}");

    // The client's fatal alert is recorded as a failed handshake; nothing reached the handler.
    eventually("failed handshake counted", || {
        server.stats.handshakes_failed() == 1
    })
    .await;
    assert_eq!(server.stats.handshakes_completed(), 0);
    server.stop().await;
}

#[tokio::test]
async fn client_with_no_trust_anchor_at_all_fails() {
    let server = TestServer::start();
    let provider = std::sync::Arc::new(rustls::crypto::ring::default_provider());
    let config = rustls::ClientConfig::builder_with_provider(provider)
        .with_safe_default_protocol_versions()
        .unwrap()
        .with_root_certificates(rustls::RootCertStore::empty())
        .with_no_client_auth();
    let error = tls_connect(server.addr, std::sync::Arc::new(config), "127.0.0.1")
        .await
        .expect_err("no anchor, no handshake");
    assert!(format!("{error:?}").contains("UnknownIssuer"));
    server.stop().await;
}

#[tokio::test]
async fn trusted_ca_does_not_vouch_for_any_other_name() {
    let server = TestServer::start();
    let config = client_trusting(&server.material.ca_cert_der);
    for name in ["evil.example", "127.0.0.2", "10.0.0.1"] {
        let error = tls_connect(server.addr, config.clone(), name)
            .await
            .expect_err("the leaf is not valid for this name");
        let text = format!("{error:?}");
        assert!(text.contains("NotValidForName"), "{name}: {text}");
    }
    server.stop().await;
}

#[tokio::test]
async fn plaintext_http_gets_no_http_response() {
    let server = TestServer::start();
    let request = format!(
        "GET / HTTP/1.1\r\nHost: 127.0.0.1:{}\r\nConnection: close\r\n\r\n",
        server.addr.port()
    );

    let received = raw_exchange(server.addr, request.as_bytes()).await;

    // Whatever came back (a TLS alert, or nothing) is not HTTP, and the connection
    // was closed by the server: `raw_exchange` returned at end of stream.
    assert!(!received.starts_with(b"HTTP/"), "{received:?}");
    assert!(!contains(&received, b"HTTP/"), "{received:?}");
    assert!(!contains(&received, GREETING));
    assert!(received.len() <= 16, "at most one small TLS alert record");
    if let Some(first) = received.first() {
        assert_eq!(*first, 0x15, "a TLS alert record, not application data");
    }

    eventually("plaintext attempt counted as a failed handshake", || {
        server.stats.handshakes_failed() == 1
    })
    .await;
    assert_eq!(server.stats.handshakes_completed(), 0);
    server.stop().await;
}

/// A well-formed TLS 1.2-only `ClientHello`: it offers suites, groups and signature
/// algorithms this server supports, but no `supported_versions` extension, so the
/// highest version on offer is 1.2 and the version is the only thing to object to.
fn tls12_client_hello() -> Vec<u8> {
    let mut body = Vec::new();
    body.extend_from_slice(&[0x03, 0x03]); // client_version: TLS 1.2
    body.extend_from_slice(&[0x5a; 32]); // random (fixed filler; not a secret)
    body.push(0); // session_id: empty
    body.extend_from_slice(&[0x00, 0x04, 0xc0, 0x2b, 0xc0, 0x2f]); // two ECDHE-AES-GCM suites
    body.extend_from_slice(&[0x01, 0x00]); // compression: null
    let extensions: [u8; 22] = [
        0x00, 0x0a, 0x00, 0x04, 0x00, 0x02, 0x00, 0x17, // supported_groups: secp256r1
        0x00, 0x0d, 0x00, 0x04, 0x00, 0x02, 0x04,
        0x03, // signature_algorithms: ecdsa_p256_sha256
        0x00, 0x0b, 0x00, 0x02, 0x01, 0x00, // ec_point_formats: uncompressed
    ];
    body.extend_from_slice(&u16::try_from(extensions.len()).unwrap().to_be_bytes());
    body.extend_from_slice(&extensions);
    let mut handshake = vec![0x01, 0x00]; // ClientHello, 24-bit length
    handshake.extend_from_slice(&u16::try_from(body.len()).unwrap().to_be_bytes());
    handshake.extend_from_slice(&body);
    let mut record = vec![0x16, 0x03, 0x01]; // handshake record
    record.extend_from_slice(&u16::try_from(handshake.len()).unwrap().to_be_bytes());
    record.extend_from_slice(&handshake);
    record
}

#[tokio::test]
async fn tls12_client_is_refused() {
    let server = TestServer::start();

    let received = raw_exchange(server.addr, &tls12_client_hello()).await;

    // A fatal alert record and nothing else: no ServerHello (0x16), no data (0x17).
    assert_eq!(received.len(), 7, "{received:?}");
    assert_eq!(received[0], 0x15, "alert record");
    assert_eq!(&received[3..5], &[0x00, 0x02], "alert length");
    assert_eq!(received[5], 0x02, "fatal");
    assert_eq!(received[6], 70, "protocol_version");

    eventually("TLS 1.2 attempt counted as a failed handshake", || {
        server.stats.handshakes_failed() == 1
    })
    .await;
    assert_eq!(server.stats.handshakes_completed(), 0);
    server.stop().await;
}

#[tokio::test]
async fn listener_is_127_0_0_1_only() {
    let server = TestServer::start();
    assert_eq!(*server.addr.ip(), Ipv4Addr::LOCALHOST);
    assert_ne!(server.addr.port(), 0);

    // `::1` is in the certificate for completeness but is not bound in v1.
    let v6 = SocketAddr::from((Ipv6Addr::LOCALHOST, server.addr.port()));
    let attempt = tokio::time::timeout(SOON, TcpStream::connect(v6)).await;
    assert!(
        matches!(attempt, Ok(Err(_))),
        "nothing of ours listens on {v6}"
    );
    server.stop().await;
}

#[tokio::test]
async fn stalled_handshake_is_dropped() {
    let limits = AcceptLimits {
        handshake_timeout: support::SHORT_TIMER,
        ..AcceptLimits::default()
    };
    let server = TestServer::start_with(limits);

    // Connect and say nothing. The server must hang up by itself, without a byte.
    let received = raw_exchange(server.addr, b"").await;
    assert!(received.is_empty(), "{received:?}");

    eventually("timeout counted", || {
        server.stats.handshakes_timed_out() == 1
    })
    .await;
    assert_eq!(server.stats.handshakes_completed(), 0);

    // The permit came back: a real client is still served.
    let config = client_trusting(&server.material.ca_cert_der);
    let mut stream = tls_connect(server.addr, config, "127.0.0.1").await.unwrap();
    assert_eq!(read_greeting(&mut stream).await, GREETING);
    server.stop().await;
}

#[tokio::test]
async fn connection_cap_drops_without_a_tls_byte_then_releases() {
    let limits = AcceptLimits {
        max_connections: 2,
        ..AcceptLimits::default()
    };
    let server = TestServer::start_with(limits);
    let config = client_trusting(&server.material.ca_cert_der);

    // Two established connections hold both permits.
    let mut held = Vec::new();
    for _ in 0..2 {
        let mut stream = tls_connect(server.addr, config.clone(), "127.0.0.1")
            .await
            .unwrap();
        assert_eq!(read_greeting(&mut stream).await, GREETING);
        held.push(stream);
    }

    // The third is dropped at once: no TLS byte, not even an alert.
    let mut third = TcpStream::connect(server.addr).await.unwrap();
    let mut received = Vec::new();
    let _ = tokio::time::timeout(SOON, third.read_to_end(&mut received))
        .await
        .expect("dropped promptly, not left to the handshake timeout");
    assert!(received.is_empty(), "{received:?}");
    assert_eq!(server.stats.refused_at_cap(), 1);
    assert_eq!(server.stats.handshakes_completed(), 2);

    // Capacity returns by itself once the pressure stops.
    drop(held);
    let mut resumed = None;
    for _ in 0..200 {
        if let Ok(mut stream) = tls_connect(server.addr, config.clone(), "127.0.0.1").await {
            if stream.read_exact(&mut [0_u8; 1]).await.is_ok() {
                resumed = Some(stream);
                break;
            }
        }
        tokio::time::sleep(support::POLL_INTERVAL).await;
    }
    assert!(
        resumed.is_some(),
        "service resumes after the cap is released"
    );
    server.stop().await;
}

#[tokio::test]
async fn shutdown_closes_the_port_and_cancels_open_connections() {
    let server = TestServer::start();
    let config = client_trusting(&server.material.ca_cert_der);
    let mut open = tls_connect(server.addr, config, "127.0.0.1").await.unwrap();
    assert_eq!(read_greeting(&mut open).await, GREETING);

    let addr = server.stop().await;

    // The held connection ends (EOF or reset) …
    let mut rest = Vec::new();
    let _ = tokio::time::timeout(SOON, open.read_to_end(&mut rest))
        .await
        .expect("the open connection is torn down");
    // … and nothing listens on the port any more.
    assert!(TcpStream::connect(addr).await.is_err());
}
