//! The Markdown rendering of the validation report (`docs/validation-report.md`).
//!
//! The same report the server embeds, as a document a reader can review in the
//! repository. The headline comes first and is computed from the counts, never
//! typed; a section the tree does not hold yet says "not yet introduced
//! (milestone Mx)" instead of disappearing.

use std::fmt::Write as _;

use super::model::{ArchiveCheck, SectionState, SectionStatus, ValidationReport};

/// The one-line truth about this commit, computed from the report.
pub(crate) fn headline(report: &ValidationReport) -> String {
    let tier1 = report
        .fixtures
        .tiers
        .iter()
        .find(|t| t.tier == "tier1")
        .map_or(0, |t| t.file_count);
    let pending = report.unverified.pending_fixture_count;
    let mut parts = vec![
        format!(
            "{tier1} tier-1 fixture{}",
            if tier1 == 1 { "" } else { "s" }
        ),
        format!(
            "{pending} fixture{} pending human verification",
            if pending == 1 { "" } else { "s" }
        ),
    ];
    if report.parameters.vintages.is_empty() {
        parts.push("no parameter vintage".to_owned());
    }
    for vintage in &report.parameters.vintages {
        parts.push(format!(
            "parameter vintage {} {} and {}",
            vintage.name,
            if vintage.locked { "locked" } else { "unlocked" },
            if vintage.verified {
                "verified"
            } else {
                "pending human verification"
            }
        ));
    }
    parts.join("; ")
}

fn state_words(status: &SectionStatus) -> String {
    match status.state {
        SectionState::NotYetIntroduced => {
            format!("not yet introduced (milestone {})", status.milestone)
        }
        SectionState::Empty => format!("empty (specified for milestone {})", status.milestone),
        SectionState::Partial => format!("partly present (milestone {})", status.milestone),
        SectionState::Present => format!("present (milestone {})", status.milestone),
    }
}

fn cell(text: &str) -> String {
    text.replace('|', "\\|").replace('\n', " ")
}

fn status_lines(out: &mut String, status: &SectionStatus) {
    let _ = writeln!(out, "**Status:** {}. {}", state_words(status), status.note);
    let _ = writeln!(out, "**Specified in:** {}.\n", status.reference);
}

fn archive_words(check: &ArchiveCheck) -> String {
    format!(
        "{} source(s), {} archived, {} checksum match, {} mismatch, {} missing",
        check.source_count,
        check.archived_count,
        check.checksum_match_count,
        check.checksum_mismatch_count,
        check.missing_count
    )
}

/// The document.
#[allow(clippy::too_many_lines)]
pub(crate) fn render(report: &ValidationReport) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "# Validation report\n");
    let _ = writeln!(
        out,
        "<!-- GENERATED by `cargo xtask validation-report` from the repository contents. Do not edit; \
regenerate. `cargo xtask validation-report --check` fails when this file is stale. -->\n"
    );
    let _ = writeln!(out, "**{}.**\n", headline(report));
    match &report.generated_on {
        Some(date) => {
            let _ = writeln!(
                out,
                "Generated for {date} (a date given to the generator; no clock is read).\n"
            );
        }
        None => {
            let _ = writeln!(
                out,
                "No generation date: none was given to the generator, and it reads no clock.\n"
            );
        }
    }
    let _ = writeln!(out, "{}\n", report.basis);
    let _ = writeln!(
        out,
        "This is the report `TESTING.md` §13 and `PLAN.md` §4.13 item 8 require at every release, \
embedded in the About page. Sections the design specifies but the tree does not hold yet are \
listed as *not yet introduced* with the milestone that introduces them, never omitted. Nothing \
marked pending is counted as validated.\n"
    );

    // Fixtures.
    let _ = writeln!(out, "## Fixtures\n");
    status_lines(&mut out, &report.fixtures.status);
    let _ = writeln!(
        out,
        "| Directory | Path | Status | Documents | By verification |"
    );
    let _ = writeln!(out, "|---|---|---|---|---|");
    for tier in &report.fixtures.tiers {
        let by_verification = if tier.by_verification.is_empty() {
            "none".to_owned()
        } else {
            tier.by_verification
                .iter()
                .map(|c| format!("{} {}", c.count, c.name))
                .collect::<Vec<_>>()
                .join("; ")
        };
        let _ = writeln!(
            out,
            "| {} | `{}/` | {} | {} | {} |",
            tier.tier,
            tier.directory,
            state_words(&tier.status),
            tier.file_count,
            cell(&by_verification)
        );
    }
    let _ = writeln!(out);
    for tier in &report.fixtures.tiers {
        let _ = writeln!(out, "### {}\n", tier.tier);
        let _ = writeln!(out, "{}\n", tier.status.note);
        if tier.by_milestone_and_verification.is_empty() {
            let _ = writeln!(out, "No fixture document.\n");
            continue;
        }
        let _ = writeln!(out, "| Milestone | Verification | Count |");
        let _ = writeln!(out, "|---|---|---|");
        for group in &tier.by_milestone_and_verification {
            let _ = writeln!(
                out,
                "| {} | {} | {} |",
                group.milestone, group.verification, group.count
            );
        }
        let _ = writeln!(out);
        if !tier.by_module.is_empty() {
            let _ = writeln!(
                out,
                "By module: {}.\n",
                tier.by_module
                    .iter()
                    .map(|c| format!("{} {}", c.count, c.name))
                    .collect::<Vec<_>>()
                    .join("; ")
            );
        }
        if !tier.review_kinds.is_empty() {
            let _ = writeln!(
                out,
                "Review kinds (`reviewedBy.kind`): {}.\n",
                tier.review_kinds
                    .iter()
                    .map(|c| format!("{} {}", c.count, c.name))
                    .collect::<Vec<_>>()
                    .join("; ")
            );
        }
        let _ = writeln!(
            out,
            "| Path | Id | Module | Milestone | Verification | Cases | Promotes to |"
        );
        let _ = writeln!(out, "|---|---|---|---|---|---|---|");
        for file in &tier.files {
            let _ = writeln!(
                out,
                "| `{}` | {} | {} | {} | {} | {} | {} |",
                file.path,
                cell(file.id.as_deref().unwrap_or("-")),
                cell(file.module.as_deref().unwrap_or("-")),
                cell(file.milestone.as_deref().unwrap_or("-")),
                cell(&file.verification),
                file.case_count,
                cell(file.promotes_to.as_deref().unwrap_or("-"))
            );
        }
        let _ = writeln!(out);
    }
    if !report.fixtures.invalid.is_empty() {
        let _ = writeln!(out, "### Unreadable fixture files\n");
        for file in &report.fixtures.invalid {
            let _ = writeln!(out, "- `{}`: {}", file.path, cell(&file.problem));
        }
        let _ = writeln!(out);
    }
    if !report.fixtures.other_directories.is_empty() {
        let _ = writeln!(out, "### Other fixture directories\n");
        for dir in &report.fixtures.other_directories {
            let _ = writeln!(out, "- `{}/`: {} file(s)", dir.name, dir.count);
        }
        let _ = writeln!(out);
    }

    // Parameters.
    let _ = writeln!(out, "## Parameter vintages\n");
    status_lines(&mut out, &report.parameters.status);
    let _ = writeln!(out, "| Vintage | Content id | Locked | Verified | Tables | Index series | Open items | Archived sources |");
    let _ = writeln!(out, "|---|---|---|---|---|---|---|---|");
    for vintage in &report.parameters.vintages {
        let _ = writeln!(
            out,
            "| {} | `{}` | {} | {} | {} | {} | {} | {} |",
            vintage.name,
            vintage.content_id,
            if vintage.locked { "yes" } else { "no" },
            if vintage.verified { "yes" } else { "no" },
            vintage.table_count,
            vintage.index_series_count,
            vintage.open_item_count,
            archive_words(&vintage.archive)
        );
    }
    let _ = writeln!(out);
    for vintage in &report.parameters.vintages {
        let _ = writeln!(out, "### {}\n", vintage.name);
        let _ = writeln!(
            out,
            "Verification values: {}.\n",
            vintage
                .verification
                .iter()
                .map(|c| format!("{} {}", c.count, c.name))
                .collect::<Vec<_>>()
                .join("; ")
        );
        let _ = writeln!(
            out,
            "| Document | Kind | Verification | Open items | Archived sources |"
        );
        let _ = writeln!(out, "|---|---|---|---|---|");
        for document in &vintage.documents {
            let _ = writeln!(
                out,
                "| `{}` | {} | {} | {} | {} |",
                document.id,
                document.kind,
                document.verification,
                document.open_item_count,
                archive_words(&document.archive)
            );
        }
        let _ = writeln!(out);
    }
    let lock = &report.parameters.lock;
    let _ = writeln!(
        out,
        "**Lock (`params/VINTAGES.lock`):** {}\n",
        if lock.present {
            let list = |dirs: &[String]| {
                if dirs.is_empty() {
                    "none".to_owned()
                } else {
                    dirs.join(", ")
                }
            };
            format!(
                "present, {} entries; verified and locked: {}; named but not verified: {} \
({} checksum mismatch, {} missing, {} unlisted). {}",
                lock.entry_count,
                list(&lock.locked_vintages),
                list(&lock.unverified_vintages),
                lock.checksum_mismatch_count,
                lock.missing_count,
                lock.unlisted_count,
                lock.note
            )
        } else {
            "absent; no vintage is locked.".to_owned()
        }
    );
    let provenance = &report.parameters.provenance;
    let _ = writeln!(
        out,
        "**Provenance archive (`params/provenance/`):** {} file(s); {} catalogued in `INDEX.toml`, \
of which {} hash to the recorded checksum, {} differ and {} are missing; the catalogue states \
`verification = {}`.\n",
        provenance.file_count,
        provenance.catalogued_count,
        provenance.checksum_match_count,
        provenance.checksum_mismatch_count,
        provenance.missing_count,
        provenance.verification.as_deref().unwrap_or("(not stated)")
    );

    // Properties.
    let _ = writeln!(out, "## Property-based and metamorphic invariants\n");
    status_lines(&mut out, &report.properties.status);
    let _ = writeln!(out, "| Crate | File | Case budget | Properties |");
    let _ = writeln!(out, "|---|---|---|---|");
    for file in &report.properties.files {
        let _ = writeln!(
            out,
            "| {} | `{}` | {} | {} |",
            file.crate_name,
            file.path,
            file.case_count
                .map_or("not stated".to_owned(), |n| n.to_string()),
            cell(&file.property_names.join(", "))
        );
    }
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "Invariant inventory (`TESTING.md` §4): {} invariants; due at M0: {}.\n",
        report.properties.invariants.len(),
        if report.properties.invariants_due_at_m0.is_empty() {
            "none".to_owned()
        } else {
            report.properties.invariants_due_at_m0.join(", ")
        }
    );
    let _ = writeln!(out, "| Id | Invariant | Crate | Milestone |");
    let _ = writeln!(out, "|---|---|---|---|");
    for invariant in &report.properties.invariants {
        let _ = writeln!(
            out,
            "| {} | {} | {} | {} |",
            invariant.id,
            cell(&invariant.name),
            cell(&invariant.crate_name),
            invariant.milestone
        );
    }
    let _ = writeln!(out);

    // Contract snapshots.
    let _ = writeln!(out, "## Contract snapshots\n");
    status_lines(&mut out, &report.contract_snapshots.status);
    for entry in &report.contract_snapshots.by_crate {
        let _ = writeln!(out, "- {}: {} snapshot file(s)", entry.name, entry.count);
    }
    let _ = writeln!(out, "\nTotal: {}.\n", report.contract_snapshots.file_count);

    // Sections that may not exist yet.
    let _ = writeln!(out, "## Corpora by section\n");
    let _ = writeln!(out, "| Section | Status | Note |");
    let _ = writeln!(out, "|---|---|---|");
    for (name, status) in [
        ("Tier-2 pinned suites", &report.tier2_suites),
        ("Tier-3 goldens", &report.tier3_goldens),
        ("Recorded oracles", &report.oracles),
        ("Mutation score", &report.mutation_score),
        ("Fuzz corpora", &report.fuzz_corpora),
        ("Security suite", &report.security_suite.status),
        ("Browser end-to-end", &report.browser_end_to_end),
        ("Performance budgets", &report.performance_budgets.status),
    ] {
        let _ = writeln!(
            out,
            "| {} | {} | {} |",
            name,
            state_words(status),
            cell(&status.note)
        );
    }
    let _ = writeln!(out);

    // Security.
    let _ = writeln!(out, "## Security suite\n");
    status_lines(&mut out, &report.security_suite.status);
    let _ = writeln!(out, "| Area | Milestone |");
    let _ = writeln!(out, "|---|---|");
    for area in &report.security_suite.areas {
        let _ = writeln!(out, "| {} | {} |", cell(&area.area), area.milestone);
    }
    let _ = writeln!(
        out,
        "\nTest ids named in test sources: {}.\n",
        if report.security_suite.test_ids_named.is_empty() {
            "none".to_owned()
        } else {
            report.security_suite.test_ids_named.join(", ")
        }
    );

    // Performance.
    let _ = writeln!(out, "## Performance budgets\n");
    status_lines(&mut out, &report.performance_budgets.status);
    let _ = writeln!(out, "| Budget | Threshold | Milestone | Measured |");
    let _ = writeln!(out, "|---|---|---|---|");
    for budget in &report.performance_budgets.budgets {
        let _ = writeln!(
            out,
            "| {} | {} | {} | not measured |",
            cell(&budget.budget),
            cell(&budget.threshold),
            budget.milestone
        );
    }
    let _ = writeln!(out);

    // Test inventory.
    let _ = writeln!(out, "## Declared tests\n");
    let _ = writeln!(out, "{}\n", report.test_inventory.note);
    let _ = writeln!(out, "| Crate | Test attributes |");
    let _ = writeln!(out, "|---|---|");
    for entry in &report.test_inventory.by_crate {
        let _ = writeln!(out, "| {} | {} |", entry.name, entry.count);
    }
    let _ = writeln!(
        out,
        "| web (node:test) | {} |\n",
        report.test_inventory.web_test_count
    );

    // Unverified.
    let _ = writeln!(out, "## Unverified\n");
    let u = &report.unverified;
    let _ = writeln!(
        out,
        "Tier-1 fixtures: {} primary-source-confirmed, {} hand-worked-reviewed. Pending human \
verification: {} fixture(s) and {} parameter document(s).\n",
        u.tier1_primary_source_confirmed_count,
        u.tier1_hand_worked_reviewed_count,
        u.pending_fixture_count,
        u.pending_parameter_document_count
    );
    let _ = writeln!(out, "### Open items of `TESTING.md` §5.2\n");
    let _ = writeln!(out, "| Item | Gate | Milestone |");
    let _ = writeln!(out, "|---|---|---|");
    for item in &u.items {
        let _ = writeln!(
            out,
            "| {} | {} | {} |",
            cell(&item.item),
            cell(&item.gate),
            item.milestone
        );
    }
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "### Open questions recorded in the parameter documents\n"
    );
    if u.parameter_open_items.is_empty() {
        let _ = writeln!(out, "None.\n");
    } else {
        for item in &u.parameter_open_items {
            let _ = writeln!(out, "- `{}`: {}", item.document, cell(&item.item));
        }
        let _ = writeln!(out);
    }

    // Refused.
    let _ = writeln!(out, "## Refused targets (`TESTING.md` §5.3)\n");
    let _ = writeln!(out, "| Target | Why, and what replaces it |");
    let _ = writeln!(out, "|---|---|");
    for target in &report.refused {
        let _ = writeln!(
            out,
            "| {} | {} |",
            cell(&target.target),
            cell(&target.reason)
        );
    }
    let _ = writeln!(out);

    // Pins.
    let _ = writeln!(out, "## Pins\n");
    let pins = &report.pins;
    let _ = writeln!(out, "- Application version: {}", pins.application_version);
    let _ = writeln!(out, "- Licence: {}", pins.licence);
    let _ = writeln!(
        out,
        "- Engine version: {}",
        pins.engine_version.as_deref().unwrap_or("none yet")
    );
    let _ = writeln!(
        out,
        "- Schema version: {}",
        pins.schema_version.as_deref().unwrap_or("none yet")
    );
    let _ = writeln!(
        out,
        "- Parameter vintage content ids: {}",
        if pins.param_vintage_content_ids.is_empty() {
            "none".to_owned()
        } else {
            pins.param_vintage_content_ids
                .iter()
                .map(|id| format!("`{id}`"))
                .collect::<Vec<_>>()
                .join(", ")
        }
    );
    let _ = writeln!(
        out,
        "- Locked parameter vintage ids: {}",
        if pins.locked_param_vintage_ids.is_empty() {
            "none".to_owned()
        } else {
            pins.locked_param_vintage_ids
                .iter()
                .map(|id| format!("`{id}`"))
                .collect::<Vec<_>>()
                .join(", ")
        }
    );
    let _ = writeln!(
        out,
        "- Binary digest: {}",
        pins.binary_digest.as_deref().unwrap_or("none yet")
    );
    let _ = writeln!(out, "\n{}", pins.note);
    out
}
